name: Auto Branch Creation

on:
  push:
    branches:
      - "release-*"

jobs:
  create_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Latest Release Branch
        id: get_latest
        run: |
          LATEST_BRANCH=$(git branch -r | grep "release-" | sed 's/origin\///' | sort -V | tail -n 1)
          if [[ -z "$LATEST_BRANCH" ]]; then
            echo "NEW_BRANCH=release-1.0" >> $GITHUB_ENV
          else
            VERSION_NUMBER=$(echo "$LATEST_BRANCH" | grep -oP '(?<=release-)\d+(?=\.0)')
            NEXT_VERSION=$((VERSION_NUMBER + 1))
            echo "NEW_BRANCH=release-${NEXT_VERSION}.0" >> $GITHUB_ENV
          fi

      - name: Create New Branch
        run: |
          git checkout -b $NEW_BRANCH
          git push origin $NEW_BRANCH
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
